name = "seedmail"
compatibility_date = "2024-01-01"

# 开发环境配置
[env.dev]
vars = {}  # 不要在这里写入实际值

# 生产环境配置
[env.production]
vars = {}  # 不要在这里写入实际值

# KV 命名空间配置
[[kv_namespaces]]
binding = "EMAILS"  # 这个是代码中使用的变量名
preview_id = "b7b8e7fb4eab40eabd3dcb1c1feea2cf"  # 开发环境使用的 KV namespace ID
id = "b7b8e7fb4eab40eabd3dcb1c1feea2cf"         # 生产环境使用的 KV namespace ID