name = "igiven-seedmail"
compatibility_date = "2024-11-10"
compatibility_flags = [ "nodejs_compat" ]

# Pages 配置
pages_build_output_dir = "dist"


[[d1_databases]]
binding = "DB"
migrations_dir = "drizzle"
database_name = "igivenmail"
database_id = "36c40381-ca08-49e5-b91d-e01d47cbb381"

# 预览环境配置
[env.preview]
vars = {}  # 不要在这里写入实际值 写在.dev.vars

# 生产环境配置
[env.production]
vars = {}  # 不要在这里写入实际值 设置在网站上 

[[env.production.d1_databases]]
binding = "DB"
migrations_dir = "drizzle"
database_name = "igivenmail"
database_id = "36c40381-ca08-49e5-b91d-e01d47cbb381"